# Generated by Django 5.2.17 on 2026-09-13 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('misc', 'Misc'), ('game', 'Game'), ('2d_art', '2D Art'), ('3d_art', '3D Art')], default='misc', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.CharField(max_length=255)),
                ('programs', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
