# Generated by Django 5.2.17 on 2026-09-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('misc', 'Misc'), ('game', 'Game'), ('web', 'Web'), ('app', 'App')], default='misc', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default="PlaceholderThumbnail.png", upload_to=''),
        ),
    ]
