# Generated by Django 5.2.17 on 2026-09-26 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_starred_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
